apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: java-app-backend-config
  namespace: java-app
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 8080
    type: HTTP
    requestPath: /health
  timeoutSec: 30
