apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-config
  namespace: java-app
data:
  welcome.html: |-
    <!DOCTYPE html>
    <html>
      <head><title>Java App</title></head>
      <body>
        <h1>Welcome to Java App - VERSION_PLACEHOLDER</h1>
      </body>
    </html>
