apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: java-app
data:
  app.name: "Java Gradle Application"
  app.version: "v1.0"
  spring.profiles.active: "production"
  welcome.message: "Welcome to Java Gradle App"