apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: java-app
data:
  app.name: "Java Gradle Application"
  app.version: "v1.0"
  app.color: "blue"
  welcome.message: "Welcome to our application - Version 1.0"