apiVersion: v1
kind: Service
metadata:
  name: java-gradle-svc
  namespace: java-gradle-ns
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"8080":{}}}'
    beta.cloud.google.com/backend-config: '{"default":"java-gradle-backendconfig"}'
spec:
  selector:
    app: java-gradle
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
