apiVersion: v1
kind: Service
metadata:
  name: java-gradle-service
  namespace: java-app
spec:
  selector:
    app: java-gradle-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
